[information]
 name = "purpleschool-nvim"
 background = "dark"
 author = 'Anton Larichev <antonlarichev@gmail.com>'

[palette]
 fg = '#fafafa'
 bg = '#101114'
 fg_inactive = '#AFB2BF'
 Color11 = '#101114'
 Color14 = '#FAFAFA'
 Color13 = '#16171D'
 Color16 = '#1c342a'
 Color12 = '#62646e'
 Color10 = '#FF7135'
 Color0 = '#b7d175'
 Color8 = '#A95EFF'
 Color15 = '#302153'
 Color3 = '#28A9FF'
 Color20 = '#8c8f9c'
 Color18 = '#404146'
 Color19 = '#4D5064'
 Color7 = '#42DD76'
 Color5 = '#585669'
 Color2 = '#D62C2C'
 Color9 = '#FF478D'
 Color4 = '#FFB638'
 Color6 = '#14E5D4'
 Color17 = '#321a1f'
 Color1 = '#524f66'

 [highlights]
 Normal = 'Color14 Color13'
 MsgArea = 'fg bg'
 ModeMsg = 'fg bg'
 MsgSeparator = 'fg bg'
 SpellBad = 'Color2 - u'
 SpellCap = 'Color4 - u'
 SpellLocal = 'Color16 - u'
 SpellRare = 'Color8 - u'
 NormalNC = 'fg bg'
 CursorLineNr = 'Color20 - b'
 Type = '- Color8'
 Comment = 'Color1 - i'
 Constant = '- Color2'
 Function = '- Color3'
 Conditional = '- Color4'
 Repeat = '- Color4'
 Operator = '- Color5'
 Identifier = '- Color9'
 Number = '- Color10'
 StatusLine = 'Color12 Color11'
 WildMenu = 'Color13 Color14'
 Pmenu = 'Color13 Color14'
 PmenuSel = 'Color14 Color15'
 PmenuThumb = 'Color13 Color14'
 DiffAdd = 'Color16'
 DiffDelete = 'Color17'
 Visual = 'Color18'
 CursorLine = 'Color18'
 ColorColumn = 'Color18'
 SignColumn = 'Color13'
 LineNr = '- Color19'
 TabLine = 'Color13 Color20'
 TabLineSel = 'Color14 Color15'
 TabLineFill = 'Color13 Color20'

[Treesitter]
 TSComment = 'link:Comment'
 TSAnnotation = 'Color3'
 TSAttribute = 'Color4'
 TSConstructor = 'Color6'
 TSType = 'Color6'
 TSPunctDelimiter = '- Color14'
